#!/bin/sh

outfile=$HOME/.trc
CONSUMER_KEY=${CONSUMER_KEY:=consumer_key}

cat > $outfile <<EOF
---
configuration:
  default_profile:
  - $OWNER
  - $CONSUMER_KEY
profiles:
  $OWNER:
    $CONSUMER_KEY:
      username: $OWNER
      consumer_key: $CONSUMER_KEY
      consumer_secret: $CONSUMER_SECRET
      token: $ACCESS_TOKEN
      secret: $ACCESS_SECRET
EOF
